name: Looping Runner

on:
  schedule:
    - cron: '0 */2 * * *'  # Alle 2 Stunden
  workflow_dispatch:

jobs:
  run-script:
    runs-on: ubuntu-latest
    timeout-minutes: 125  # Sicherheitspuffer – endet nach 2h 5min

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Install System Dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y tor screen wget unzip

      - name: Disable systemd Tor
        run: |
          sudo systemctl disable tor || true

      - name: Install geckodriver
        run: |
          GECKO_VERSION=$(curl -s https://api.github.com/repos/mozilla/geckodriver/releases/latest | grep '"tag_name":' | sed -E 's/.*"v([^"]+)".*/\1/')
          wget -q https://github.com/mozilla/geckodriver/releases/download/v$GECKO_VERSION/geckodriver-v$GECKO_VERSION-linux64.tar.gz
          tar -xzf geckodriver-v$GECKO_VERSION-linux64.tar.gz
          sudo mv geckodriver /usr/local/bin/

      - name: Set up Python 3.11 virtual environment
        run: |
          python3.11 -m venv venv
          source venv/bin/activate
          pip install --upgrade pip
          pip install selenium requests

      - name: Start TOR and Script in Screens
        run: |
          screen -dmS tor_session bash -c "tor -f ./torrc"
          screen -dmS py_session bash -c "source venv/bin/activate && python3 ./LINUX.py"

      - name: Sleep for 2 hours
        run: sleep 7200
