name: Looping Runner

on:
  schedule:
    - cron: '0 */2 * * *'  # Alle 2 Stunden
  workflow_dispatch:

jobs:
  run-script:
    runs-on: ubuntu-latest
    timeout-minutes: 125

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Set up Python 3.11
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'

      - name: Install System Dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y tor screen wget unzip

      - name: Disable systemd Tor
        run: |
          sudo systemctl disable tor || true

      - name: Install geckodriver
        run: |
          GECKO_VERSION=$(curl -s https://api.github.com/repos/mozilla/geckodriver/releases/latest | grep '"tag_name":' | sed -E 's/.*"v([^"]+)".*/\1/')
          wget -q https://github.com/mozilla/geckodriver/releases/download/v$GECKO_VERSION/geckodriver-v$GECKO_VERSION-linux64.tar.gz
          tar -xzf geckodriver-v$GECKO_VERSION-linux64.tar.gz
          sudo mv geckodriver /usr/local/bin/

      - name: Set up virtual environment and install packages
        run: |
          python3 -m venv venv
          source venv/bin/activate
          pip install --upgrade pip
          pip install selenium requests

      - name: Start TOR in screen (detached)
        run: |
          screen -dmS tor_session bash -c "tor -f ./torrc"

      - name: Run Python script (interactive)
        run: |
          source venv/bin/activate
          python3 ./LINUX.py
